# Generated by Django 5.0.6 on 2024-07-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorio_categoria_cor_marca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório", "verbose_name_plural": "Acessórios"},
        ),
        migrations.AddField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
